- name: Assign IP address to VM
  hosts: localhost
  connection: local
  become: yes
  vars:
    ip_range: 10.0.3.
    start_ip: 200
    end_ip: 250
    gateway_ip: 10.0.0.1
    vm_name: your_vm_name
    hostname: your_vm_hostname
  tasks:
    - name: Get current network interface name
      shell: "ip route get 8.8.8.8 | awk '{print $5; exit}'"
      register: iface_result

    - name: Get current IP address
      shell: "hostname -I | awk '{print $1}'"
      register: current_ip

    - name: Create updated IP address configuration
      set_fact:
        updated_config: |
          network:
            version: 2
            ethernets:
              {{ iface_result.stdout }}:
                dhcp4: no
                addresses: [{{ ip_range }}{{ start_ip }}/{{ netmask }}]
                gateway4: {{ gateway_ip }}
                nameservers:
                  addresses: [8.8.8.8, 8.8.4.4]
            renderer: networkd

    - name: Replace IP address configuration in 00-installer-config.yaml
      copy:
        content: "{{ updated_config }}"
        dest: /etc/netplan/00-installer-config.yaml

    - name: Apply new network configuration
      command: netplan apply
      become: yes

    - name: Restart networking service
      service:
        name: systemd-networkd
        state: restarted
