---
- name: Assign IP address to VM
  hosts: localhost
  connection: local
  become: yes
  vars:
    ip_range: 10.0.3.
    start_ip: 200
    end_ip: 250
    vm_name: your_vm_name
    hostname: your_vm_hostname
  tasks:
    - name: Get network interface name
      shell: "grep -E '^iface .* inet static$' /etc/network/interfaces | awk '{print $2}'"
      register: iface_result
      changed_when: false

    - name: Get current IP address
      shell: "hostname -I | awk '{print $1}'"
      register: current_ip

    - name: Assign static IP address
      lineinfile:
        path: /etc/network/interfaces
        line: |
          auto {{ iface_result.stdout }}
          iface {{ iface_result.stdout }} inet static
          address {{ ip_range }}{{ item }}
          netmask 255.255.255.0
          gateway 10.0.0.1
      with_sequence: start={{ start_ip }} end={{ end_ip }}
      when: current_ip.stdout != "{{ ip_range }}{{ item }}"

    - name: Restart network
      service:
        name: networking
        state: restarted
      when: current_ip.stdout != "{{ ip_range }}{{ start_ip }}"

    - name: Add hostname to hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ ip_range }}{{ item }} {{ hostname }}"
      with_sequence: start={{ start_ip }} end={{ end_ip }}

