---
- name: Configure netplan with static IP
  hosts: localhost
  become: true

  tasks:
    - name: Get default IPv4 interface name
      set_fact:
        default_ipv4_interface: "{{ ansible_default_ipv4.interface }}"

    - name: Generate random IP address
      set_fact:
        ip_address: "10.0.3.{{ 200 + (range(0, 50)|random) }}"

    - name: Create netplan configuration file
      copy:
        content: |
          network:
            renderer: networkd
            ethernets:
              "{{ default_ipv4_interface }}":
                addresses:
                  - "{{ ip_address }}/24"
                gateway4: 10.0.0.1
                nameservers:
                  addresses: [4.2.2.2, 8.8.8.8]
                routes:
                  - to: default
                    via: 10.0.0.1
            version: 2
        dest: /etc/netplan/01-netcfg.yaml
        mode: 0644

    - name: Apply netplan configuration changes
      command: netplan apply
