- name: Assign IP address to VM
  hosts: localhost
  connection: local
  become: yes
  vars:
    ip_range: 10.0.3.
    start_ip: 200
    end_ip: 250
    vm_name: your_vm_name
    hostname: your_vm_hostname
  args:
    arg_gateway: "10.0.0.1"
  tasks:
    - name: Get network interface name
      shell: "ip -o -4 route show to default | awk '{print $5}'"
      register: iface_result
      changed_when: false

    - name: Get current IP address
      shell: "hostname -I | awk '{print $1}'"
      register: current_ip

    - name: Assign static IP address
      lineinfile:
        path: /etc/netplan/00-installer-config.yaml
        insertafter: '^ethernets:$'
        line: |
          {{ iface_result.stdout }}:
            addresses:
              - {{ ip_range }}{{ item }}/24
            gateway4: {{ arg_gateway }}
            nameservers:
              addresses: [4.2.2.2, 8.8.8.8]
      with_sequence: start={{ start_ip }} end={{ end_ip }}
      when: current_ip.stdout != "{{ ip_range }}{{ item }}"

    - name: Apply network configuration changes
      command: "netplan apply"
      when: current_ip.stdout != "{{ ip_range }}{{ start_ip }}"
