---
- name: Configure netplan with static IP
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Get current machine IP address
      set_fact:
        current_ip: "{{ ansible_default_ipv4.address }}"

    - name: Add current machine to playbook inventory
      add_host:
        name: "{{ current_ip }}"
        groups: your_ubuntu_servers

- name: Apply netplan configuration
  hosts: your_ubuntu_servers
  become: true

  tasks:
    - name: Generate random IP address
      set_fact:
        ip_address: "10.0.3.{{ 200 + (range(0, 50)|random) }}"

    - name: Create netplan configuration file
      copy:
        content: |
          network:
            renderer: networkd
            ethernets:
              "{{ ansible_default_ipv4.interface }}":
                addresses:
                  - "{{ ip_address }}/24"
                gateway4: 10.0.0.1
                nameservers:
                  addresses: [4.2.2.2, 8.8.8.8]
                routes:
                  - to: default
                    via: 10.0.0.1
            version: 2
        dest: /etc/netplan/01-netcfg.yaml
        mode: 0644

    - name: Apply netplan configuration changes
      command: netplan apply
