---
- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
    - name: Add Neovim PPA repository
      apt_repository:
        repo: ppa:neovim-ppa/stable
        state: present
    - name: Add Alacritty repository key
      apt_key:
        url: https://packages.alacritty.org/debian/alacritty.asc
    - name: Add Alacritty repository
      apt_repository:
        repo: deb https://packages.alacritty.org/debian/ stable main
        state: present
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Neovim and Alacritty
      apt:
        name:
          - neovim
          - alacritty
        state: present
