---
- name: Install Visual Studio Code
  hosts: localhost
  become: true

  tasks:
    - name: Install wget and gpg
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - gpg

    - name: Download Microsoft GPG key
      shell: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
      args:
        chdir: /tmp

    - name: Install Microsoft GPG key
      copy:
        src: packages.microsoft.gpg
        dest: /etc/apt/keyrings/packages.microsoft.gpg
        owner: root
        group: root
        mode: 0644

    - name: Add Visual Studio Code repository
      copy:
        content: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
        dest: /etc/apt/sources.list.d/vscode.list
        owner: root
        group: root
        mode: 0644

    - name: Remove temporary GPG key file
      file:
        path: packages.microsoft.gpg
        state: absent

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Visual Studio Code
      apt:
        name: code
        state: present
